# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - aula-08-projeto-final-hmg

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_f788bd54380c4c459f91c1e78a083171 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4ecf5eff84b6484fb9a7197507f31906 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_f788bd54380c4c459f91c1e78a083171 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aula-08-projeto-final-hmg'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7ea4d4d33dd64e71a664979566719bdf }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f788bd54380c4c459f91c1e78a083171 }}/appsvc/staticsite:${{ github.sha }}'